# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
#     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.

done = False
sum = 0
prev = 0
fib = 1

while not done :
  fib = prev + fib
  prev = fib - prev

  if fib % 2 == 0 :
    sum += fib
  # end if

  if fib > 4000000 :
    done = True
  # end if
#end while

# Should be 4,613,732
print sum
